[package]
name = "litex-pac"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[dependencies]
bare-metal = "1.0.0"
riscv = "0.6.0"
vcell = "0.1.2"
riscv-rt = { optional = true, version = "0.8.0" }

[features]
rt = ["riscv-rt"]
